import{useEffect,useMemo,useState}from'react';
import{Mail,MapPin,MessageCircle,Phone,Search,Users}from'lucide-react';
import{AudienceSidebar}from'./Audience';
import{whatsappInviteUrl}from'./whatsappInvite';

type Group={id:string;name:string};
type Person={id:string;name:string;email:string;phone?:string|null;stayArea?:string|null;labels:string[];role:'DADE'|'VOLUNTEER';avatarUrl?:string|null;harmonyGroup?:Group|null;mutualLoveGroup?:Group|null;cooperationUnit?:Group|null};
type Directory={scope:{harmony:string;mutualLove:string};people:Person[]};
const token=()=>JSON.parse(localStorage.getItem('ln_session')||'null')?.token;
const sessionUser=()=>JSON.parse(localStorage.getItem('ln_session')||'null')?.user;

export default function CooperationPeople(){
  const[data,setData]=useState<Directory|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(true);
  useEffect(()=>{fetch('/api/people/cooperation',{headers:{Authorization:`Bearer ${token()}`}}).then(async response=>{const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error||'Could not load people');return body}).then(setData).catch(reason=>setError(reason.message)).finally(()=>setBusy(false))},[]);
  const people=useMemo(()=>{const value=query.trim().toLowerCase();if(!value)return data?.people||[];return(data?.people||[]).filter(person=>[person.name,person.email,person.phone,person.stayArea,person.role,...person.labels].some(field=>field?.toLowerCase().includes(value)))},[data,query]);
  return <div className="dash audienceDash"><AudienceSidebar active="people"/><section className="content cooperationPeoplePage"><div className="top"><div><small>COOPERATION LEADER / PEOPLE</small><h1>People</h1><p>DADE and Volunteer accounts in your assigned Harmony and MutualLove groups.</p></div></div>{error?<div className="panel emptyState cooperationPeopleError">{error}</div>:busy?<div className="panel emptyState">Loading people…</div>:<><div className="cooperationPeopleScope"><div><span>HARMONY</span><b>{data?.scope.harmony}</b></div><div><span>MUTUALLOVE</span><b>{data?.scope.mutualLove}</b></div><strong>{data?.people.length||0}<small>People</small></strong></div><label className="cooperationPeopleSearch"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search people" aria-label="Search people"/></label>{people.length?<div className="cooperationPeopleGrid">{people.map(person=>{const inviteUrl=person.phone?whatsappInviteUrl({phone:person.phone,recipientName:person.name,inviterName:sessionUser()?.name||'Your Cooperation Leader',origin:window.location.origin}):'';return <article className="panel cooperationPersonCard" key={person.id}><div className="cooperationPersonHead">{person.avatarUrl?<img src={person.avatarUrl} alt=""/>:<span>{person.name.slice(0,2).toUpperCase()}</span>}<div><h2>{person.name}</h2><em>{person.role==='DADE'?'DADE':'Volunteer'}</em></div></div><div className="cooperationPersonDetails"><a href={`mailto:${person.email}`}><Mail/>{person.email}</a>{person.phone&&<a href={`tel:${person.phone}`}><Phone/>{person.phone}</a>}{person.stayArea&&<span><MapPin/>{person.stayArea}</span>}<span><Users/>{[person.harmonyGroup?.name,person.mutualLoveGroup?.name,person.cooperationUnit?.name].filter(Boolean).join(' › ')}</span></div>{person.labels.length>0&&<div className="cooperationPersonLabels">{person.labels.map(label=><span key={label}>{label}</span>)}</div>}{inviteUrl&&<a className="cooperationWhatsAppInvite" href={inviteUrl} target="_blank" rel="noreferrer" aria-label={`Invite ${person.name} via WhatsApp`}><MessageCircle/>Invite via WhatsApp</a>}</article>})}</div>:<div className="panel emptyState">No matching people found.</div>}</>}</section></div>
}
